import type { Avatar } from '@/lib/orderAvatars';

// The faces we generated for this brand, and the one that got the job.
//
// Sits under the cuts because it answers a question the cuts raise rather than
// one they leave open: why does the person in my ad look like that. A client
// who can see the alternatives reads the answer as a decision. A client who
// cannot read it as whatever the tool produced.
//
// Small on purpose, and stripped back to the faces on 1 Sep. It was a row of
// cards carrying a paragraph each, which made a footnote read like a second
// article and pushed the thing somebody came here to do off the screen. The
// faces are the argument. Reading three defences of them is not.
//
// `note` on an avatar is still carried by lib/orderAvatars and deliberately not
// rendered. It is the reasoning behind a pick, worth keeping written down and
// worth having if this ever earns a detail view, and not worth the room here.

export default function AvatarLineup({
  avatars,
  /** Named so the one closing line can say whose kit this is. */
  brand,
}: {
  avatars: Avatar[];
  brand?: string | null;
}) {
  if (avatars.length === 0) return null;

  const who = brand?.trim() || 'this brand';

  return (
    <section className="faces">
      <h2>The faces we tried</h2>

      <ul className="faces-grid">
        {avatars.map((avatar) => (
          <li className={avatar.picked ? 'face-card face-on' : 'face-card'} key={avatar.slug}>
            <div className="face-shot">
              {avatar.clipUrl ? (
                // A still cannot show a delivery, so a face we have moving
                // footage of plays it. muted and loop rather than autoplay
                // with sound: a lineup that starts talking at somebody is a
                // page they close.
                <video
                  src={avatar.clipUrl}
                  poster={avatar.imageUrl}
                  controls
                  muted
                  loop
                  playsInline
                  preload="none"
                />
              ) : (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={avatar.imageUrl} alt={avatar.name} loading="lazy" />
              )}
              {avatar.picked && <span className="face-badge">In your ad</span>}
            </div>
            <span className="face-name">{avatar.name}</span>
          </li>
        ))}
      </ul>

      {/* One line, not a section. The brand kit paragraph that used to sit here
          was a pitch for the next order underneath the one being reviewed, and
          it read as one. What is true and worth saying is why this face and not
          the others. */}
      <p className="faces-kit">
        All generated by us for {who}. We kept the one we found most appropriate for
        this script.
      </p>
    </section>
  );
}
