import type { Avatar } from '@/lib/orderAvatars';

// The faces we generated for this brand, and the one that got the job.
//
// Sits under the cuts because it answers a question the cuts raise rather than
// one they leave open: why does the person in my ad look like that. A client
// who can see the alternatives reads the answer as a decision. A client who
// cannot read it as whatever the tool produced.
//
// It is also the first visible piece of the brand kit. The lineup is per
// brand, not per ad, which is the thing worth saying out loud here: the next
// order starts from a face that already exists rather than from a fresh
// stranger, and the same goes for the voice and the type.

export default function AvatarLineup({
  avatars,
  /** Named so the closing line can say whose kit this is. */
  brand,
}: {
  avatars: Avatar[];
  brand?: string | null;
}) {
  if (avatars.length === 0) return null;

  const picked = avatars.find((a) => a.picked) ?? null;
  const who = brand?.trim() || 'this brand';

  return (
    <section className="faces">
      <h2>The faces we tried before this one</h2>
      <p className="faces-lede">
        Every one of these was generated by us for {who}. We ran them against the same
        script and kept the one that held it.
      </p>

      <ul className="faces-grid">
        {avatars.map((avatar) => (
          <li className={avatar.picked ? 'face-card face-on' : 'face-card'} key={avatar.slug}>
            <div className="face-shot">
              {avatar.clipUrl ? (
                // A still cannot show a delivery, so a face we have moving
                // footage of plays it. muted and loop rather than autoplay
                // with sound: a lineup that starts talking at somebody is a
                // page they close.
                <video
                  src={avatar.clipUrl}
                  poster={avatar.imageUrl}
                  controls
                  muted
                  loop
                  playsInline
                  preload="none"
                />
              ) : (
                // eslint-disable-next-line @next/next/no-img-element
                <img src={avatar.imageUrl} alt={avatar.name} loading="lazy" />
              )}
              {avatar.picked && <span className="face-badge">In your ad</span>}
            </div>

            <div className="face-said">
              <span className="face-name">{avatar.name}</span>
              {avatar.kind && <span className="face-kind">{avatar.kind}</span>}
              {/* Labelled as our read, not as a fact about the face. Same
                  split the cut cards draw between the story and our read of
                  it. */}
              {avatar.note && <p className="face-note">{avatar.note}</p>}
            </div>
          </li>
        ))}
      </ul>

      <div className="ord-brief-block faces-kit">
        <h2>Where this goes next</h2>
        <p>
          {picked
            ? `${picked.name} is now ${who}'s face. `
            : ''}
          From here we keep a kit for {who}: the face, how it speaks, and the type and
          colour that go around it. Every order after this one starts from that kit, so
          the ads look like they came from the same brand rather than from the same tool.
          If you want a different face for a different audience, we add it to the kit
          rather than starting over.
        </p>
      </div>
    </section>
  );
}
